services:
  app:
    image: otel-app
    container_name: My-Otel-App
    ports:
      - "8080:8080"  # Expose the app on port 8080
    restart: always
    depends_on:
      - collector-agent
      - collector-gateway
      - jaeger  # Ensure that Jaeger and the collector are up before starting the app
      - redis   # Ensure Redis is available before starting the app
    environment:
      - REDIS_HOST=redis  # Set Redis hostname to link to the Redis service
      - REDIS_PORT=6379   # Redis default port
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    
  jaeger:
    image: jaegertracing/all-in-one:1.27
    container_name: jaeger
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elastic:9200 
    ports: 
      - 5775:5775/udp    # Thrift UDP for traces
      - 6831:6831/udp    # Thrift UDP for traces
      - 6832:6832/udp    # Thrift UDP for traces
      - 5778:5778        # For local testing, queries
      - 16686:16686      # Jaeger UI
      - 14268:14268      # Jaeger collector HTTP
      - 14250:14250      # Jaeger gRPC
      - 9411:9411        # Zipkin-compatible trace collector
    deploy:
      restart_policy:
        condition: on-failure

  collector-gateway:
    image: otel/opentelemetry-collector:0.29.0
    container_name: otel-collector2
    volumes: 
      - ./config/collector-gateway.yml:/etc/otel-collector-config.yaml  # Mount the collector config
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4319:4319"      # OTLP gRPC receiver (default OTLP gRPC port)
      - "4320:4320"      # OTLP HTTP receiver (default OTLP HTTP port)
  
  collector-agent:
    image: otel/opentelemetry-collector:0.29.0
    container_name: otel-collector1
    volumes:
      - ./config/collector-agent.yml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4317:4317"
      - "4318:4318"


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # Expose Redis on the default port
    deploy:
      restart_policy:
        condition: on-failure
