receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4320  # Accepts traces on HTTP OTLP endpoint
      grpc:
        endpoint: 0.0.0.0:4319  # Listen for OTLP data over gRPC
  

processors:
  batch:
    timeout: 1s  # Batch the traces for more efficient exporting
  resource:
    attributes:
      - key: test-key
        value: "gateway"
        action: insert  # Inserts the custom attribute into each trace

exporters:
  jaeger:
    endpoint: jaeger:14250  #  "jaeger" is the hostname of the Jaeger instance in my network
    insecure: true  # This is not good practice in prod
  logging:
    loglevel: info  # Logs traces to console for debugging

service:
  pipelines:
    traces:
      receivers: [otlp]  # Receives OTLP traces from the application
      processors: [batch, resource]  # Apply batch processing and resource attributes
      exporters: [logging, jaeger]  # Export traces to Jaeger and log them to console
